[workspace]
resolver = "2"
members = [
    "libnres",
    "nres-cli",
    "packer",
    "resource-viewer",
    "texture-decoder",
    "unpacker",
]

[profile.release]
codegen-units = 1
lto = true
strip = true
