[graph]
all-features = true

[advisories]
yanked = "deny"

[bans]
multiple-versions = "allow"
wildcards = "deny"
deny = [
  { name = "native-tls" },
  { name = "openssl" },
  { name = "openssl-sys" },
]

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "GPL-2.0-only",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
